name: Validate Config

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-config:
    runs-on: ubuntu-slim
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2026.4.24

      - name: Validate config
        run: |
          set -euo pipefail

          for file in *.json*; do
            npm exec --yes --package=renovate@43.142.0 -- renovate-config-validator --strict --no-global "$file"
          done
