name: Validate Config

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-config:
    runs-on: ubuntu-slim
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24

      - name: Validate config
        run: npm exec --yes --package=renovate@43.123.6 -- renovate-config-validator --strict --no-global default.json
